url: "https://tomasfontalvoherrera.com"
baseurl: ""  # Deja esto vacío si es un sitio raíz (no un subdirectorio)
title: "Tomás Fontalvo Herrera" # the name of your site, e.g. ACME Corp.
description: "Investigador Senior en Gestión y Administración"
